/*
 * Generated by Robotoworks Mechanoid
 */
package com.justeat.migrations;

import android.database.sqlite.SQLiteDatabase;
import com.robotoworks.mechanoid.db.SQLiteMigration;

public class DefaultTakeawaysDBMigrationV34 extends SQLiteMigration {
	@Override
	public void onBeforeUp(SQLiteDatabase db) {}
	
	@Override
	public void up(SQLiteDatabase db) {
		db.execSQL(
			"alter table orders add column delivery_address text "
		);	
		db.execSQL(
			"alter table orders add column delivery_city text "
		);	
		db.execSQL(
			"alter table orders add column delivery_postcode text "
		);	
	}
	
	@Override
	public void onAfterUp(SQLiteDatabase db) {}
}
