/*
 * Generated by Robotoworks Mechanoid
 */
package com.justeat.migrations;

import android.database.sqlite.SQLiteDatabase;
import com.robotoworks.mechanoid.db.SQLiteMigration;

public class DefaultTakeawaysDBMigrationV17 extends SQLiteMigration {
	@Override
	public void onBeforeUp(SQLiteDatabase db) {}
	
	@Override
	public void up(SQLiteDatabase db) {
		db.execSQL(
			"drop table orders "
		);	
		db.execSQL(
			"create table orders ( " +
			"_id integer primary key autoincrement, " +
			"restaurant_jeid integer, " +
			"restaurant_name text, " +
			"restaurant_address text, " +
			"restaurant_city text, " +
			"restaurant_postcode text, " +
			"restaurant_logo_standard_res_url text, " +
			"menu_jeid integer, " +
			"is_delivery boolean, " +
			"basket_jeid text, " +
			"order_number text, " +
			"estimated_delivery_time text, " +
			"total real, " +
			"created integer, " +
			"quantity integer, " +
			"restaurant_phone text, " +
			"unique(order_number) on conflict replace " +
			") "
		);	
	}
	
	@Override
	public void onAfterUp(SQLiteDatabase db) {}
}
