/*
 * Generated by Robotoworks Mechanoid
 */
package com.justeat.migrations;

import android.database.sqlite.SQLiteDatabase;
import com.robotoworks.mechanoid.db.SQLiteMigration;

public class DefaultTakeawaysDBMigrationV27 extends SQLiteMigration {
	@Override
	public void onBeforeUp(SQLiteDatabase db) {}
	
	@Override
	public void up(SQLiteDatabase db) {
		db.execSQL(
			"drop trigger update_product_basket_quantity_on_basket_items_deleted "
		);	
		db.execSQL(
			"drop trigger update_product_basket_quantity_on_basket_items_inserted "
		);	
		db.execSQL(
			"drop trigger update_product_basket_quantity_on_basket_items_updated "
		);	
		db.execSQL(
			"drop trigger update_product_basket_quantity_on_products_inserted "
		);	
	}
	
	@Override
	public void onAfterUp(SQLiteDatabase db) {}
}
