/*
 * Generated by Robotoworks Mechanoid
 */
package com.justeat.migrations;

import android.database.sqlite.SQLiteDatabase;
import com.robotoworks.mechanoid.db.SQLiteMigration;

public class DefaultTakeawaysDBMigrationV14 extends SQLiteMigration {
	@Override
	public void onBeforeUp(SQLiteDatabase db) {}
	
	@Override
	public void up(SQLiteDatabase db) {
		db.execSQL(
			"create table address_search_result ( " +
			"_id integer primary key autoincrement, " +
			"zipcode text, " +
			"city text, " +
			"access_count integer, " +
			"last_time_accessed text, " +
			"unique ( " +
			"zipcode " +
			") on conflict ignore " +
			") "
		);	
	}
	
	@Override
	public void onAfterUp(SQLiteDatabase db) {}
}
