/*
 * Generated by Robotoworks Mechanoid
 */
package com.justeat.migrations;

import android.database.sqlite.SQLiteDatabase;
import com.robotoworks.mechanoid.db.SQLiteMigration;

public class DefaultTakeawaysDBMigrationV5 extends SQLiteMigration {
	@Override
	public void onBeforeUp(SQLiteDatabase db) {}
	
	@Override
	public void up(SQLiteDatabase db) {
		db.execSQL(
			"create table restaurant_opening_times ( " +
			"_id integer primary key autoincrement, " +
			"restaurant_jeid integer, " +
			"day integer, " +
			"day_text text, " +
			"open text, " +
			"closed text, " +
			"rank integer, " +
			"unique(restaurant_jeid, day) on conflict replace " +
			") "
		);	
		db.execSQL(
			"alter table restaurants add column description text "
		);	
	}
	
	@Override
	public void onAfterUp(SQLiteDatabase db) {}
}
