/*
 * generated by Xtext
 */
package com.justeat.mickeydb.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.justeat.mickeydb.ui.internal.MickeyLangActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MickeyLangExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return MickeyLangActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return MickeyLangActivator.getInstance().getInjector(MickeyLangActivator.COM_JUSTEAT_MICKEYDB_MICKEYLANG);
	}
	
}
