/*
 * generated by Xtext
 */
package com.justeat.mickeydb;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class MickeyLangStandaloneSetup extends MickeyLangStandaloneSetupGenerated{

	public static void doSetup() {
		new MickeyLangStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

