/*
 * generated by Xtext
 */
package com.justeat.mickeydb.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MickeyLangAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("com/justeat/mickeydb/parser/antlr/internal/InternalMickeyLang.tokens");
	}
}
