/*
 * Generated by Mickey DB
 */
package com.example.mickeydbexample.migrations;

import android.database.sqlite.SQLiteDatabase;
import com.justeat.mickeydb.Migration;

public class DefaultTakeawaysDBMigrationVegetarianMigration extends Migration {
	@Override
	public void onBeforeUp(SQLiteDatabase db) {}
	
	@Override
	public void up(SQLiteDatabase db) {
		db.execSQL(
			"alter table restaurants add column has_vegetarian boolean "
		);	
	}
	
	@Override
	public void onAfterUp(SQLiteDatabase db) {}
}
