/**
 * generated by Xtext
 */
package com.justeat.mickeydb.validation;

import com.justeat.mickeydb.validation.AbstractMickeyLangValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class MickeyLangValidator extends AbstractMickeyLangValidator {
}
