/*
 * Generated by Mickey DB
 */
package com.example.mickeydbexample.data;

import android.content.Context;
import com.example.mickeydbexample.data.AbstractTakeawaysDBOpenHelper;


public class TakeawaysDBOpenHelper extends AbstractTakeawaysDBOpenHelper {
	public TakeawaysDBOpenHelper(Context context) {
		super(context);
	}
}
