/*
 * Generated by Robotoworks Mechanoid
 */
package com.justeat;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import com.robotoworks.mechanoid.db.MechanoidSQLiteOpenHelper;
import com.robotoworks.mechanoid.db.SQLiteMigration;

import com.justeat.migrations.DefaultTakeawaysDBMigrationVinitial_migration;
import com.justeat.migrations.DefaultTakeawaysDBMigrationVdescription_migration;
import com.justeat.migrations.DefaultTakeawaysDBMigrationVvegetarian_migration;

public abstract class AbstractTakeawaysDBOpenHelper extends MechanoidSQLiteOpenHelper {
	private static final String DATABASE_NAME = "TakeawaysDB.db";

	public static final int VERSION = vegetarian_migration;

	public interface Sources {
		String RESTAURANTS = "restaurants";
		String ALL_RESTAURANTS = "all_restaurants";
	}

	public AbstractTakeawaysDBOpenHelper(Context context) {
		super(context, DATABASE_NAME, null, VERSION);
	}

	public AbstractTakeawaysDBOpenHelper(Context context, String name) {
		super(context, name, null, VERSION);
	}

	@Override
	public void onCreate(SQLiteDatabase db) {
		applyMigrations(db, 0, VERSION);
	}
	
	@Override
	public void onOpen(SQLiteDatabase db) {
		super.onOpen(db);
		
		db.execSQL(
			"create temp view all_restaurants as " +
			"select " +
			"t._id as takeaway_id, " +
			"t.name as takeaway_name, " +
			"t.description as takeaway_description, " +
			"t.city as takeaway_city, " +
			"t.cuisines as takeaway_cuisines, " +
			"t.rating as takeaway_rating " +
			"from restaurants as t "
		);	
	}

	@Override
	protected SQLiteMigration createMigration(int version) {
		switch(version) {
			case 0:
				return createTakeawaysDBMigrationVinitial_migration();
			case 1:
				return createTakeawaysDBMigrationVdescription_migration();
			case 2:
				return createTakeawaysDBMigrationVvegetarian_migration();
			default:
				throw new IllegalStateException("No migration for version " + version);
		}
	}
	
	protected SQLiteMigration createTakeawaysDBMigrationVinitial_migration() {
		return new DefaultTakeawaysDBMigrationVinitial_migration();
	}
	protected SQLiteMigration createTakeawaysDBMigrationVdescription_migration() {
		return new DefaultTakeawaysDBMigrationVdescription_migration();
	}
	protected SQLiteMigration createTakeawaysDBMigrationVvegetarian_migration() {
		return new DefaultTakeawaysDBMigrationVvegetarian_migration();
	}
}
