/*
 * Generated by Robotoworks Mechanoid
 */
package com.justeat;

import android.content.ContentResolver;
import android.database.Cursor;
import android.os.Bundle;
import android.os.Parcel;
import android.os.Parcelable;
import android.net.Uri;
import com.justeat.TakeawaysDBContract.OrderHistoryItems;
import com.justeat.TakeawaysDBContract.OrderHistoryItems.Builder;
import com.robotoworks.mechanoid.util.Closeables;
import com.robotoworks.mechanoid.db.ActiveRecord;
import com.robotoworks.mechanoid.db.ActiveRecordFactory;
import com.robotoworks.mechanoid.Mechanoid;
import com.robotoworks.mechanoid.db.AbstractValuesBuilder;

public class OrderHistoryItemsRecord extends ActiveRecord implements Parcelable {

	private static ActiveRecordFactory<OrderHistoryItemsRecord> sFactory = new ActiveRecordFactory<OrderHistoryItemsRecord>() {
		@Override
		public OrderHistoryItemsRecord create(Cursor c) {
			return fromCursor(c);
		}
		
		@Override
		public String[] getProjection() {
			return PROJECTION;
		}

        @Override
                    public Uri getContentUri() {
                        return OrderHistoryItems.CONTENT_URI;
                    }
                };

    			public static ActiveRecordFactory<OrderHistoryItemsRecord> getFactory() {
		return sFactory;
	}

    public static final Parcelable.Creator<OrderHistoryItemsRecord> CREATOR 
    	= new Parcelable.Creator<OrderHistoryItemsRecord>() {
        public OrderHistoryItemsRecord createFromParcel(Parcel in) {
            return new OrderHistoryItemsRecord(in);
        }

        public OrderHistoryItemsRecord[] newArray(int size) {
            return new OrderHistoryItemsRecord[size];
        }
    };
    
    public static String[] PROJECTION = {
    	OrderHistoryItems._ID,
    	OrderHistoryItems.BASKET_JEID,
    	OrderHistoryItems.BASKET_ITEM_JEID,
    	OrderHistoryItems.RESTAURANT_JEID,
    	OrderHistoryItems.MENU_JEID,
    	OrderHistoryItems.CATEGORY_JEID,
    	OrderHistoryItems.PRODUCT_JEID,
    	OrderHistoryItems.IS_COMPLEX,
    	OrderHistoryItems.PRODUCT_NAME,
    	OrderHistoryItems.PRODUCT_SYNONYM,
    	OrderHistoryItems.PRODUCT_HAS_ACCESSORIES,
    	OrderHistoryItems.PRODUCT_HAS_COMBO_OPTIONS,
    	OrderHistoryItems.DESCRIPTION,
    	OrderHistoryItems.PRODUCT_PRICE,
    	OrderHistoryItems.TOTAL_PRICE,
    	OrderHistoryItems.IS_TIPS,
    	OrderHistoryItems.MENU_SORT_KEY,
    	OrderHistoryItems.GROUP_KEY,
    	OrderHistoryItems.USER
    };
    
    public interface Indices {
    	int _ID = 0;
    	int BASKET_JEID = 1;
    	int BASKET_ITEM_JEID = 2;
    	int RESTAURANT_JEID = 3;
    	int MENU_JEID = 4;
    	int CATEGORY_JEID = 5;
    	int PRODUCT_JEID = 6;
    	int IS_COMPLEX = 7;
    	int PRODUCT_NAME = 8;
    	int PRODUCT_SYNONYM = 9;
    	int PRODUCT_HAS_ACCESSORIES = 10;
    	int PRODUCT_HAS_COMBO_OPTIONS = 11;
    	int DESCRIPTION = 12;
    	int PRODUCT_PRICE = 13;
    	int TOTAL_PRICE = 14;
    	int IS_TIPS = 15;
    	int MENU_SORT_KEY = 16;
    	int GROUP_KEY = 17;
    	int USER = 18;
    }
    
    private String mBasketJeid;
    private boolean mBasketJeidDirty;
    private String mBasketItemJeid;
    private boolean mBasketItemJeidDirty;
    private long mRestaurantJeid;
    private boolean mRestaurantJeidDirty;
    private long mMenuJeid;
    private boolean mMenuJeidDirty;
    private long mCategoryJeid;
    private boolean mCategoryJeidDirty;
    private long mProductJeid;
    private boolean mProductJeidDirty;
    private boolean mIsComplex;
    private boolean mIsComplexDirty;
    private String mProductName;
    private boolean mProductNameDirty;
    private String mProductSynonym;
    private boolean mProductSynonymDirty;
    private boolean mProductHasAccessories;
    private boolean mProductHasAccessoriesDirty;
    private boolean mProductHasComboOptions;
    private boolean mProductHasComboOptionsDirty;
    private String mDescription;
    private boolean mDescriptionDirty;
    private double mProductPrice;
    private boolean mProductPriceDirty;
    private double mTotalPrice;
    private boolean mTotalPriceDirty;
    private boolean mIsTips;
    private boolean mIsTipsDirty;
    private String mMenuSortKey;
    private boolean mMenuSortKeyDirty;
    private String mGroupKey;
    private boolean mGroupKeyDirty;
    private String mUser;
    private boolean mUserDirty;
    
    @Override
    protected String[] _getProjection() {
    	return PROJECTION;
    }
    
    public void setBasketJeid(String basketJeid) {
    	mBasketJeid = basketJeid;
    	mBasketJeidDirty = true;
    }
    
    public String getBasketJeid() {
    	return mBasketJeid;
    }
    
    public void setBasketItemJeid(String basketItemJeid) {
    	mBasketItemJeid = basketItemJeid;
    	mBasketItemJeidDirty = true;
    }
    
    public String getBasketItemJeid() {
    	return mBasketItemJeid;
    }
    
    public void setRestaurantJeid(long restaurantJeid) {
    	mRestaurantJeid = restaurantJeid;
    	mRestaurantJeidDirty = true;
    }
    
    public long getRestaurantJeid() {
    	return mRestaurantJeid;
    }
    
    public void setMenuJeid(long menuJeid) {
    	mMenuJeid = menuJeid;
    	mMenuJeidDirty = true;
    }
    
    public long getMenuJeid() {
    	return mMenuJeid;
    }
    
    public void setCategoryJeid(long categoryJeid) {
    	mCategoryJeid = categoryJeid;
    	mCategoryJeidDirty = true;
    }
    
    public long getCategoryJeid() {
    	return mCategoryJeid;
    }
    
    public void setProductJeid(long productJeid) {
    	mProductJeid = productJeid;
    	mProductJeidDirty = true;
    }
    
    public long getProductJeid() {
    	return mProductJeid;
    }
    
    public void setIsComplex(boolean isComplex) {
    	mIsComplex = isComplex;
    	mIsComplexDirty = true;
    }
    
    public boolean getIsComplex() {
    	return mIsComplex;
    }
    
    public void setProductName(String productName) {
    	mProductName = productName;
    	mProductNameDirty = true;
    }
    
    public String getProductName() {
    	return mProductName;
    }
    
    public void setProductSynonym(String productSynonym) {
    	mProductSynonym = productSynonym;
    	mProductSynonymDirty = true;
    }
    
    public String getProductSynonym() {
    	return mProductSynonym;
    }
    
    public void setProductHasAccessories(boolean productHasAccessories) {
    	mProductHasAccessories = productHasAccessories;
    	mProductHasAccessoriesDirty = true;
    }
    
    public boolean getProductHasAccessories() {
    	return mProductHasAccessories;
    }
    
    public void setProductHasComboOptions(boolean productHasComboOptions) {
    	mProductHasComboOptions = productHasComboOptions;
    	mProductHasComboOptionsDirty = true;
    }
    
    public boolean getProductHasComboOptions() {
    	return mProductHasComboOptions;
    }
    
    public void setDescription(String description) {
    	mDescription = description;
    	mDescriptionDirty = true;
    }
    
    public String getDescription() {
    	return mDescription;
    }
    
    public void setProductPrice(double productPrice) {
    	mProductPrice = productPrice;
    	mProductPriceDirty = true;
    }
    
    public double getProductPrice() {
    	return mProductPrice;
    }
    
    public void setTotalPrice(double totalPrice) {
    	mTotalPrice = totalPrice;
    	mTotalPriceDirty = true;
    }
    
    public double getTotalPrice() {
    	return mTotalPrice;
    }
    
    public void setIsTips(boolean isTips) {
    	mIsTips = isTips;
    	mIsTipsDirty = true;
    }
    
    public boolean getIsTips() {
    	return mIsTips;
    }
    
    public void setMenuSortKey(String menuSortKey) {
    	mMenuSortKey = menuSortKey;
    	mMenuSortKeyDirty = true;
    }
    
    public String getMenuSortKey() {
    	return mMenuSortKey;
    }
    
    public void setGroupKey(String groupKey) {
    	mGroupKey = groupKey;
    	mGroupKeyDirty = true;
    }
    
    public String getGroupKey() {
    	return mGroupKey;
    }
    
    public void setUser(String user) {
    	mUser = user;
    	mUserDirty = true;
    }
    
    public String getUser() {
    	return mUser;
    }
    
    
    public OrderHistoryItemsRecord() {
    	super(OrderHistoryItems.CONTENT_URI);
	}
	
	private OrderHistoryItemsRecord(Parcel in) {
    	super(OrderHistoryItems.CONTENT_URI);
    	
		setId(in.readLong());
		
		mBasketJeid = in.readString();
		mBasketItemJeid = in.readString();
		mRestaurantJeid = in.readLong();
		mMenuJeid = in.readLong();
		mCategoryJeid = in.readLong();
		mProductJeid = in.readLong();
		mIsComplex = (in.readInt() > 0);
		mProductName = in.readString();
		mProductSynonym = in.readString();
		mProductHasAccessories = (in.readInt() > 0);
		mProductHasComboOptions = (in.readInt() > 0);
		mDescription = in.readString();
		mProductPrice = in.readDouble();
		mTotalPrice = in.readDouble();
		mIsTips = (in.readInt() > 0);
		mMenuSortKey = in.readString();
		mGroupKey = in.readString();
		mUser = in.readString();
		
		boolean[] dirtyFlags = new boolean[18];
		in.readBooleanArray(dirtyFlags);
		mBasketJeidDirty = dirtyFlags[0];
		mBasketItemJeidDirty = dirtyFlags[1];
		mRestaurantJeidDirty = dirtyFlags[2];
		mMenuJeidDirty = dirtyFlags[3];
		mCategoryJeidDirty = dirtyFlags[4];
		mProductJeidDirty = dirtyFlags[5];
		mIsComplexDirty = dirtyFlags[6];
		mProductNameDirty = dirtyFlags[7];
		mProductSynonymDirty = dirtyFlags[8];
		mProductHasAccessoriesDirty = dirtyFlags[9];
		mProductHasComboOptionsDirty = dirtyFlags[10];
		mDescriptionDirty = dirtyFlags[11];
		mProductPriceDirty = dirtyFlags[12];
		mTotalPriceDirty = dirtyFlags[13];
		mIsTipsDirty = dirtyFlags[14];
		mMenuSortKeyDirty = dirtyFlags[15];
		mGroupKeyDirty = dirtyFlags[16];
		mUserDirty = dirtyFlags[17];
	}
	
	@Override
	public int describeContents() {
	    return 0;
	}
	
	@Override
	public void writeToParcel(Parcel dest, int flags) {
		dest.writeLong(getId());
		dest.writeString(mBasketJeid);
		dest.writeString(mBasketItemJeid);
		dest.writeLong(mRestaurantJeid);
		dest.writeLong(mMenuJeid);
		dest.writeLong(mCategoryJeid);
		dest.writeLong(mProductJeid);
		dest.writeInt(mIsComplex ? 1 : 0);
		dest.writeString(mProductName);
		dest.writeString(mProductSynonym);
		dest.writeInt(mProductHasAccessories ? 1 : 0);
		dest.writeInt(mProductHasComboOptions ? 1 : 0);
		dest.writeString(mDescription);
		dest.writeDouble(mProductPrice);
		dest.writeDouble(mTotalPrice);
		dest.writeInt(mIsTips ? 1 : 0);
		dest.writeString(mMenuSortKey);
		dest.writeString(mGroupKey);
		dest.writeString(mUser);
		dest.writeBooleanArray(new boolean[] {
			mBasketJeidDirty,
			mBasketItemJeidDirty,
			mRestaurantJeidDirty,
			mMenuJeidDirty,
			mCategoryJeidDirty,
			mProductJeidDirty,
			mIsComplexDirty,
			mProductNameDirty,
			mProductSynonymDirty,
			mProductHasAccessoriesDirty,
			mProductHasComboOptionsDirty,
			mDescriptionDirty,
			mProductPriceDirty,
			mTotalPriceDirty,
			mIsTipsDirty,
			mMenuSortKeyDirty,
			mGroupKeyDirty,
			mUserDirty
		});
	}
	
	@Override
	protected AbstractValuesBuilder createBuilder() {
		Builder builder = OrderHistoryItems.newBuilder();

		if(mBasketJeidDirty) {
			builder.setBasketJeid(mBasketJeid);
		}
		if(mBasketItemJeidDirty) {
			builder.setBasketItemJeid(mBasketItemJeid);
		}
		if(mRestaurantJeidDirty) {
			builder.setRestaurantJeid(mRestaurantJeid);
		}
		if(mMenuJeidDirty) {
			builder.setMenuJeid(mMenuJeid);
		}
		if(mCategoryJeidDirty) {
			builder.setCategoryJeid(mCategoryJeid);
		}
		if(mProductJeidDirty) {
			builder.setProductJeid(mProductJeid);
		}
		if(mIsComplexDirty) {
			builder.setIsComplex(mIsComplex);
		}
		if(mProductNameDirty) {
			builder.setProductName(mProductName);
		}
		if(mProductSynonymDirty) {
			builder.setProductSynonym(mProductSynonym);
		}
		if(mProductHasAccessoriesDirty) {
			builder.setProductHasAccessories(mProductHasAccessories);
		}
		if(mProductHasComboOptionsDirty) {
			builder.setProductHasComboOptions(mProductHasComboOptions);
		}
		if(mDescriptionDirty) {
			builder.setDescription(mDescription);
		}
		if(mProductPriceDirty) {
			builder.setProductPrice(mProductPrice);
		}
		if(mTotalPriceDirty) {
			builder.setTotalPrice(mTotalPrice);
		}
		if(mIsTipsDirty) {
			builder.setIsTips(mIsTips);
		}
		if(mMenuSortKeyDirty) {
			builder.setMenuSortKey(mMenuSortKey);
		}
		if(mGroupKeyDirty) {
			builder.setGroupKey(mGroupKey);
		}
		if(mUserDirty) {
			builder.setUser(mUser);
		}
		
		return builder;
	}
	
    @Override
	public void makeDirty(boolean dirty){
		mBasketJeidDirty = dirty;
		mBasketItemJeidDirty = dirty;
		mRestaurantJeidDirty = dirty;
		mMenuJeidDirty = dirty;
		mCategoryJeidDirty = dirty;
		mProductJeidDirty = dirty;
		mIsComplexDirty = dirty;
		mProductNameDirty = dirty;
		mProductSynonymDirty = dirty;
		mProductHasAccessoriesDirty = dirty;
		mProductHasComboOptionsDirty = dirty;
		mDescriptionDirty = dirty;
		mProductPriceDirty = dirty;
		mTotalPriceDirty = dirty;
		mIsTipsDirty = dirty;
		mMenuSortKeyDirty = dirty;
		mGroupKeyDirty = dirty;
		mUserDirty = dirty;
	}

	@Override
	protected void setPropertiesFromCursor(Cursor c) {
		setId(c.getLong(Indices._ID));
		setBasketJeid(c.getString(Indices.BASKET_JEID));
		setBasketItemJeid(c.getString(Indices.BASKET_ITEM_JEID));
		setRestaurantJeid(c.getLong(Indices.RESTAURANT_JEID));
		setMenuJeid(c.getLong(Indices.MENU_JEID));
		setCategoryJeid(c.getLong(Indices.CATEGORY_JEID));
		setProductJeid(c.getLong(Indices.PRODUCT_JEID));
		setIsComplex(c.getInt(Indices.IS_COMPLEX) > 0);
		setProductName(c.getString(Indices.PRODUCT_NAME));
		setProductSynonym(c.getString(Indices.PRODUCT_SYNONYM));
		setProductHasAccessories(c.getInt(Indices.PRODUCT_HAS_ACCESSORIES) > 0);
		setProductHasComboOptions(c.getInt(Indices.PRODUCT_HAS_COMBO_OPTIONS) > 0);
		setDescription(c.getString(Indices.DESCRIPTION));
		setProductPrice(c.getDouble(Indices.PRODUCT_PRICE));
		setTotalPrice(c.getDouble(Indices.TOTAL_PRICE));
		setIsTips(c.getInt(Indices.IS_TIPS) > 0);
		setMenuSortKey(c.getString(Indices.MENU_SORT_KEY));
		setGroupKey(c.getString(Indices.GROUP_KEY));
		setUser(c.getString(Indices.USER));
	}
	
	public static OrderHistoryItemsRecord fromCursor(Cursor c) {
	    OrderHistoryItemsRecord item = new OrderHistoryItemsRecord();
	    
		item.setPropertiesFromCursor(c);
		
		item.makeDirty(false);
		
	    return item;
	}
	
	public static OrderHistoryItemsRecord fromBundle(Bundle bundle, String key) {
		bundle.setClassLoader(OrderHistoryItemsRecord.class.getClassLoader());
		return bundle.getParcelable(key);
	}
	
	public static OrderHistoryItemsRecord get(long id) {
	    Cursor c = null;
	    
	    ContentResolver resolver = Mechanoid.getContentResolver();
	    
	    try {
	        c = resolver.query(OrderHistoryItems.CONTENT_URI.buildUpon()
			.appendPath(String.valueOf(id)).build(), PROJECTION, null, null, null);
	        
	        if(!c.moveToFirst()) {
	            return null;
	        }
	        
	        return fromCursor(c);
	    } finally {
	        Closeables.closeSilently(c);
	    }
	}
}
