/*
 * Generated by Robotoworks Mechanoid
 */
package com.justeat;

import android.content.ContentResolver;
import android.database.Cursor;
import android.os.Bundle;
import android.os.Parcel;
import android.os.Parcelable;
import android.net.Uri;
import com.justeat.TakeawaysDBContract.Restaurants;
import com.justeat.TakeawaysDBContract.Restaurants.Builder;
import com.robotoworks.mechanoid.util.Closeables;
import com.robotoworks.mechanoid.db.ActiveRecord;
import com.robotoworks.mechanoid.db.ActiveRecordFactory;
import com.robotoworks.mechanoid.Mechanoid;
import com.robotoworks.mechanoid.db.AbstractValuesBuilder;

public class RestaurantsRecord extends ActiveRecord implements Parcelable {

	private static ActiveRecordFactory<RestaurantsRecord> sFactory = new ActiveRecordFactory<RestaurantsRecord>() {
		@Override
		public RestaurantsRecord create(Cursor c) {
			return fromCursor(c);
		}
		
		@Override
		public String[] getProjection() {
			return PROJECTION;
		}

        @Override
                    public Uri getContentUri() {
                        return Restaurants.CONTENT_URI;
                    }
                };

    			public static ActiveRecordFactory<RestaurantsRecord> getFactory() {
		return sFactory;
	}

    public static final Parcelable.Creator<RestaurantsRecord> CREATOR 
    	= new Parcelable.Creator<RestaurantsRecord>() {
        public RestaurantsRecord createFromParcel(Parcel in) {
            return new RestaurantsRecord(in);
        }

        public RestaurantsRecord[] newArray(int size) {
            return new RestaurantsRecord[size];
        }
    };
    
    public static String[] PROJECTION = {
    	Restaurants._ID,
    	Restaurants.JEID,
    	Restaurants.NAME,
    	Restaurants.ADDRESS,
    	Restaurants.CITY,
    	Restaurants.POSTCODE,
    	Restaurants.SEARCH_QUERY,
    	Restaurants.CUISINES,
    	Restaurants.DEALS,
    	Restaurants.DEFAULT_DISPLAY_RANK,
    	Restaurants.IS_HALAL,
    	Restaurants.IS_NEW,
    	Restaurants.IS_OPEN_NOW_FOR_DELIVERY,
    	Restaurants.IS_OPEN_NOW_FOR_COLLECTION,
    	Restaurants.IS_OPEN_NOW,
    	Restaurants.IS_SPONSORED,
    	Restaurants.IS_TEMPORARILY_OFFLINE,
    	Restaurants.LOGO_STANDARD_RES_URL,
    	Restaurants.RATING,
    	Restaurants.REASON_WHY_TEMPORARILY_OFFLINE,
    	Restaurants.NUM_RATINGS,
    	Restaurants.DESCRIPTION,
    	Restaurants.LATITUDE,
    	Restaurants.LONGITUDE,
    	Restaurants.OPENING_TIME,
    	Restaurants.UNIQUE_NAME,
    	Restaurants.DRIVE_DISTANCE,
    	Restaurants.RATING_AVERAGE,
    	Restaurants.SHOW_SMILEY,
    	Restaurants.SMILEY_DATE,
    	Restaurants.SMILEY_RESULT,
    	Restaurants.SMILEY_ELITE,
    	Restaurants.SMILEY_URL,
    	Restaurants.DEAL_DISPLAY_RANK,
    	Restaurants.HAS_DEALS,
    	Restaurants.MAX_DISCOUNT_PERCENT
    };
    
    public interface Indices {
    	int _ID = 0;
    	int JEID = 1;
    	int NAME = 2;
    	int ADDRESS = 3;
    	int CITY = 4;
    	int POSTCODE = 5;
    	int SEARCH_QUERY = 6;
    	int CUISINES = 7;
    	int DEALS = 8;
    	int DEFAULT_DISPLAY_RANK = 9;
    	int IS_HALAL = 10;
    	int IS_NEW = 11;
    	int IS_OPEN_NOW_FOR_DELIVERY = 12;
    	int IS_OPEN_NOW_FOR_COLLECTION = 13;
    	int IS_OPEN_NOW = 14;
    	int IS_SPONSORED = 15;
    	int IS_TEMPORARILY_OFFLINE = 16;
    	int LOGO_STANDARD_RES_URL = 17;
    	int RATING = 18;
    	int REASON_WHY_TEMPORARILY_OFFLINE = 19;
    	int NUM_RATINGS = 20;
    	int DESCRIPTION = 21;
    	int LATITUDE = 22;
    	int LONGITUDE = 23;
    	int OPENING_TIME = 24;
    	int UNIQUE_NAME = 25;
    	int DRIVE_DISTANCE = 26;
    	int RATING_AVERAGE = 27;
    	int SHOW_SMILEY = 28;
    	int SMILEY_DATE = 29;
    	int SMILEY_RESULT = 30;
    	int SMILEY_ELITE = 31;
    	int SMILEY_URL = 32;
    	int DEAL_DISPLAY_RANK = 33;
    	int HAS_DEALS = 34;
    	int MAX_DISCOUNT_PERCENT = 35;
    }
    
    private long mJeid;
    private boolean mJeidDirty;
    private String mName;
    private boolean mNameDirty;
    private String mAddress;
    private boolean mAddressDirty;
    private String mCity;
    private boolean mCityDirty;
    private String mPostcode;
    private boolean mPostcodeDirty;
    private String mSearchQuery;
    private boolean mSearchQueryDirty;
    private String mCuisines;
    private boolean mCuisinesDirty;
    private String mDeals;
    private boolean mDealsDirty;
    private long mDefaultDisplayRank;
    private boolean mDefaultDisplayRankDirty;
    private boolean mIsHalal;
    private boolean mIsHalalDirty;
    private boolean mIsNew;
    private boolean mIsNewDirty;
    private boolean mIsOpenNowForDelivery;
    private boolean mIsOpenNowForDeliveryDirty;
    private boolean mIsOpenNowForCollection;
    private boolean mIsOpenNowForCollectionDirty;
    private boolean mIsOpenNow;
    private boolean mIsOpenNowDirty;
    private boolean mIsSponsored;
    private boolean mIsSponsoredDirty;
    private boolean mIsTemporarilyOffline;
    private boolean mIsTemporarilyOfflineDirty;
    private String mLogoStandardResUrl;
    private boolean mLogoStandardResUrlDirty;
    private double mRating;
    private boolean mRatingDirty;
    private String mReasonWhyTemporarilyOffline;
    private boolean mReasonWhyTemporarilyOfflineDirty;
    private long mNumRatings;
    private boolean mNumRatingsDirty;
    private String mDescription;
    private boolean mDescriptionDirty;
    private double mLatitude;
    private boolean mLatitudeDirty;
    private double mLongitude;
    private boolean mLongitudeDirty;
    private long mOpeningTime;
    private boolean mOpeningTimeDirty;
    private String mUniqueName;
    private boolean mUniqueNameDirty;
    private double mDriveDistance;
    private boolean mDriveDistanceDirty;
    private double mRatingAverage;
    private boolean mRatingAverageDirty;
    private boolean mShowSmiley;
    private boolean mShowSmileyDirty;
    private long mSmileyDate;
    private boolean mSmileyDateDirty;
    private long mSmileyResult;
    private boolean mSmileyResultDirty;
    private boolean mSmileyElite;
    private boolean mSmileyEliteDirty;
    private String mSmileyUrl;
    private boolean mSmileyUrlDirty;
    private long mDealDisplayRank;
    private boolean mDealDisplayRankDirty;
    private boolean mHasDeals;
    private boolean mHasDealsDirty;
    private long mMaxDiscountPercent;
    private boolean mMaxDiscountPercentDirty;
    
    @Override
    protected String[] _getProjection() {
    	return PROJECTION;
    }
    
    public void setJeid(long jeid) {
    	mJeid = jeid;
    	mJeidDirty = true;
    }
    
    public long getJeid() {
    	return mJeid;
    }
    
    public void setName(String name) {
    	mName = name;
    	mNameDirty = true;
    }
    
    public String getName() {
    	return mName;
    }
    
    public void setAddress(String address) {
    	mAddress = address;
    	mAddressDirty = true;
    }
    
    public String getAddress() {
    	return mAddress;
    }
    
    public void setCity(String city) {
    	mCity = city;
    	mCityDirty = true;
    }
    
    public String getCity() {
    	return mCity;
    }
    
    public void setPostcode(String postcode) {
    	mPostcode = postcode;
    	mPostcodeDirty = true;
    }
    
    public String getPostcode() {
    	return mPostcode;
    }
    
    public void setSearchQuery(String searchQuery) {
    	mSearchQuery = searchQuery;
    	mSearchQueryDirty = true;
    }
    
    public String getSearchQuery() {
    	return mSearchQuery;
    }
    
    public void setCuisines(String cuisines) {
    	mCuisines = cuisines;
    	mCuisinesDirty = true;
    }
    
    public String getCuisines() {
    	return mCuisines;
    }
    
    public void setDeals(String deals) {
    	mDeals = deals;
    	mDealsDirty = true;
    }
    
    public String getDeals() {
    	return mDeals;
    }
    
    public void setDefaultDisplayRank(long defaultDisplayRank) {
    	mDefaultDisplayRank = defaultDisplayRank;
    	mDefaultDisplayRankDirty = true;
    }
    
    public long getDefaultDisplayRank() {
    	return mDefaultDisplayRank;
    }
    
    public void setIsHalal(boolean isHalal) {
    	mIsHalal = isHalal;
    	mIsHalalDirty = true;
    }
    
    public boolean getIsHalal() {
    	return mIsHalal;
    }
    
    public void setIsNew(boolean isNew) {
    	mIsNew = isNew;
    	mIsNewDirty = true;
    }
    
    public boolean getIsNew() {
    	return mIsNew;
    }
    
    public void setIsOpenNowForDelivery(boolean isOpenNowForDelivery) {
    	mIsOpenNowForDelivery = isOpenNowForDelivery;
    	mIsOpenNowForDeliveryDirty = true;
    }
    
    public boolean getIsOpenNowForDelivery() {
    	return mIsOpenNowForDelivery;
    }
    
    public void setIsOpenNowForCollection(boolean isOpenNowForCollection) {
    	mIsOpenNowForCollection = isOpenNowForCollection;
    	mIsOpenNowForCollectionDirty = true;
    }
    
    public boolean getIsOpenNowForCollection() {
    	return mIsOpenNowForCollection;
    }
    
    public void setIsOpenNow(boolean isOpenNow) {
    	mIsOpenNow = isOpenNow;
    	mIsOpenNowDirty = true;
    }
    
    public boolean getIsOpenNow() {
    	return mIsOpenNow;
    }
    
    public void setIsSponsored(boolean isSponsored) {
    	mIsSponsored = isSponsored;
    	mIsSponsoredDirty = true;
    }
    
    public boolean getIsSponsored() {
    	return mIsSponsored;
    }
    
    public void setIsTemporarilyOffline(boolean isTemporarilyOffline) {
    	mIsTemporarilyOffline = isTemporarilyOffline;
    	mIsTemporarilyOfflineDirty = true;
    }
    
    public boolean getIsTemporarilyOffline() {
    	return mIsTemporarilyOffline;
    }
    
    public void setLogoStandardResUrl(String logoStandardResUrl) {
    	mLogoStandardResUrl = logoStandardResUrl;
    	mLogoStandardResUrlDirty = true;
    }
    
    public String getLogoStandardResUrl() {
    	return mLogoStandardResUrl;
    }
    
    public void setRating(double rating) {
    	mRating = rating;
    	mRatingDirty = true;
    }
    
    public double getRating() {
    	return mRating;
    }
    
    public void setReasonWhyTemporarilyOffline(String reasonWhyTemporarilyOffline) {
    	mReasonWhyTemporarilyOffline = reasonWhyTemporarilyOffline;
    	mReasonWhyTemporarilyOfflineDirty = true;
    }
    
    public String getReasonWhyTemporarilyOffline() {
    	return mReasonWhyTemporarilyOffline;
    }
    
    public void setNumRatings(long numRatings) {
    	mNumRatings = numRatings;
    	mNumRatingsDirty = true;
    }
    
    public long getNumRatings() {
    	return mNumRatings;
    }
    
    public void setDescription(String description) {
    	mDescription = description;
    	mDescriptionDirty = true;
    }
    
    public String getDescription() {
    	return mDescription;
    }
    
    public void setLatitude(double latitude) {
    	mLatitude = latitude;
    	mLatitudeDirty = true;
    }
    
    public double getLatitude() {
    	return mLatitude;
    }
    
    public void setLongitude(double longitude) {
    	mLongitude = longitude;
    	mLongitudeDirty = true;
    }
    
    public double getLongitude() {
    	return mLongitude;
    }
    
    public void setOpeningTime(long openingTime) {
    	mOpeningTime = openingTime;
    	mOpeningTimeDirty = true;
    }
    
    public long getOpeningTime() {
    	return mOpeningTime;
    }
    
    public void setUniqueName(String uniqueName) {
    	mUniqueName = uniqueName;
    	mUniqueNameDirty = true;
    }
    
    public String getUniqueName() {
    	return mUniqueName;
    }
    
    public void setDriveDistance(double driveDistance) {
    	mDriveDistance = driveDistance;
    	mDriveDistanceDirty = true;
    }
    
    public double getDriveDistance() {
    	return mDriveDistance;
    }
    
    public void setRatingAverage(double ratingAverage) {
    	mRatingAverage = ratingAverage;
    	mRatingAverageDirty = true;
    }
    
    public double getRatingAverage() {
    	return mRatingAverage;
    }
    
    public void setShowSmiley(boolean showSmiley) {
    	mShowSmiley = showSmiley;
    	mShowSmileyDirty = true;
    }
    
    public boolean getShowSmiley() {
    	return mShowSmiley;
    }
    
    public void setSmileyDate(long smileyDate) {
    	mSmileyDate = smileyDate;
    	mSmileyDateDirty = true;
    }
    
    public long getSmileyDate() {
    	return mSmileyDate;
    }
    
    public void setSmileyResult(long smileyResult) {
    	mSmileyResult = smileyResult;
    	mSmileyResultDirty = true;
    }
    
    public long getSmileyResult() {
    	return mSmileyResult;
    }
    
    public void setSmileyElite(boolean smileyElite) {
    	mSmileyElite = smileyElite;
    	mSmileyEliteDirty = true;
    }
    
    public boolean getSmileyElite() {
    	return mSmileyElite;
    }
    
    public void setSmileyUrl(String smileyUrl) {
    	mSmileyUrl = smileyUrl;
    	mSmileyUrlDirty = true;
    }
    
    public String getSmileyUrl() {
    	return mSmileyUrl;
    }
    
    public void setDealDisplayRank(long dealDisplayRank) {
    	mDealDisplayRank = dealDisplayRank;
    	mDealDisplayRankDirty = true;
    }
    
    public long getDealDisplayRank() {
    	return mDealDisplayRank;
    }
    
    public void setHasDeals(boolean hasDeals) {
    	mHasDeals = hasDeals;
    	mHasDealsDirty = true;
    }
    
    public boolean getHasDeals() {
    	return mHasDeals;
    }
    
    public void setMaxDiscountPercent(long maxDiscountPercent) {
    	mMaxDiscountPercent = maxDiscountPercent;
    	mMaxDiscountPercentDirty = true;
    }
    
    public long getMaxDiscountPercent() {
    	return mMaxDiscountPercent;
    }
    
    
    public RestaurantsRecord() {
    	super(Restaurants.CONTENT_URI);
	}
	
	private RestaurantsRecord(Parcel in) {
    	super(Restaurants.CONTENT_URI);
    	
		setId(in.readLong());
		
		mJeid = in.readLong();
		mName = in.readString();
		mAddress = in.readString();
		mCity = in.readString();
		mPostcode = in.readString();
		mSearchQuery = in.readString();
		mCuisines = in.readString();
		mDeals = in.readString();
		mDefaultDisplayRank = in.readLong();
		mIsHalal = (in.readInt() > 0);
		mIsNew = (in.readInt() > 0);
		mIsOpenNowForDelivery = (in.readInt() > 0);
		mIsOpenNowForCollection = (in.readInt() > 0);
		mIsOpenNow = (in.readInt() > 0);
		mIsSponsored = (in.readInt() > 0);
		mIsTemporarilyOffline = (in.readInt() > 0);
		mLogoStandardResUrl = in.readString();
		mRating = in.readDouble();
		mReasonWhyTemporarilyOffline = in.readString();
		mNumRatings = in.readLong();
		mDescription = in.readString();
		mLatitude = in.readDouble();
		mLongitude = in.readDouble();
		mOpeningTime = in.readLong();
		mUniqueName = in.readString();
		mDriveDistance = in.readDouble();
		mRatingAverage = in.readDouble();
		mShowSmiley = (in.readInt() > 0);
		mSmileyDate = in.readLong();
		mSmileyResult = in.readLong();
		mSmileyElite = (in.readInt() > 0);
		mSmileyUrl = in.readString();
		mDealDisplayRank = in.readLong();
		mHasDeals = (in.readInt() > 0);
		mMaxDiscountPercent = in.readLong();
		
		boolean[] dirtyFlags = new boolean[35];
		in.readBooleanArray(dirtyFlags);
		mJeidDirty = dirtyFlags[0];
		mNameDirty = dirtyFlags[1];
		mAddressDirty = dirtyFlags[2];
		mCityDirty = dirtyFlags[3];
		mPostcodeDirty = dirtyFlags[4];
		mSearchQueryDirty = dirtyFlags[5];
		mCuisinesDirty = dirtyFlags[6];
		mDealsDirty = dirtyFlags[7];
		mDefaultDisplayRankDirty = dirtyFlags[8];
		mIsHalalDirty = dirtyFlags[9];
		mIsNewDirty = dirtyFlags[10];
		mIsOpenNowForDeliveryDirty = dirtyFlags[11];
		mIsOpenNowForCollectionDirty = dirtyFlags[12];
		mIsOpenNowDirty = dirtyFlags[13];
		mIsSponsoredDirty = dirtyFlags[14];
		mIsTemporarilyOfflineDirty = dirtyFlags[15];
		mLogoStandardResUrlDirty = dirtyFlags[16];
		mRatingDirty = dirtyFlags[17];
		mReasonWhyTemporarilyOfflineDirty = dirtyFlags[18];
		mNumRatingsDirty = dirtyFlags[19];
		mDescriptionDirty = dirtyFlags[20];
		mLatitudeDirty = dirtyFlags[21];
		mLongitudeDirty = dirtyFlags[22];
		mOpeningTimeDirty = dirtyFlags[23];
		mUniqueNameDirty = dirtyFlags[24];
		mDriveDistanceDirty = dirtyFlags[25];
		mRatingAverageDirty = dirtyFlags[26];
		mShowSmileyDirty = dirtyFlags[27];
		mSmileyDateDirty = dirtyFlags[28];
		mSmileyResultDirty = dirtyFlags[29];
		mSmileyEliteDirty = dirtyFlags[30];
		mSmileyUrlDirty = dirtyFlags[31];
		mDealDisplayRankDirty = dirtyFlags[32];
		mHasDealsDirty = dirtyFlags[33];
		mMaxDiscountPercentDirty = dirtyFlags[34];
	}
	
	@Override
	public int describeContents() {
	    return 0;
	}
	
	@Override
	public void writeToParcel(Parcel dest, int flags) {
		dest.writeLong(getId());
		dest.writeLong(mJeid);
		dest.writeString(mName);
		dest.writeString(mAddress);
		dest.writeString(mCity);
		dest.writeString(mPostcode);
		dest.writeString(mSearchQuery);
		dest.writeString(mCuisines);
		dest.writeString(mDeals);
		dest.writeLong(mDefaultDisplayRank);
		dest.writeInt(mIsHalal ? 1 : 0);
		dest.writeInt(mIsNew ? 1 : 0);
		dest.writeInt(mIsOpenNowForDelivery ? 1 : 0);
		dest.writeInt(mIsOpenNowForCollection ? 1 : 0);
		dest.writeInt(mIsOpenNow ? 1 : 0);
		dest.writeInt(mIsSponsored ? 1 : 0);
		dest.writeInt(mIsTemporarilyOffline ? 1 : 0);
		dest.writeString(mLogoStandardResUrl);
		dest.writeDouble(mRating);
		dest.writeString(mReasonWhyTemporarilyOffline);
		dest.writeLong(mNumRatings);
		dest.writeString(mDescription);
		dest.writeDouble(mLatitude);
		dest.writeDouble(mLongitude);
		dest.writeLong(mOpeningTime);
		dest.writeString(mUniqueName);
		dest.writeDouble(mDriveDistance);
		dest.writeDouble(mRatingAverage);
		dest.writeInt(mShowSmiley ? 1 : 0);
		dest.writeLong(mSmileyDate);
		dest.writeLong(mSmileyResult);
		dest.writeInt(mSmileyElite ? 1 : 0);
		dest.writeString(mSmileyUrl);
		dest.writeLong(mDealDisplayRank);
		dest.writeInt(mHasDeals ? 1 : 0);
		dest.writeLong(mMaxDiscountPercent);
		dest.writeBooleanArray(new boolean[] {
			mJeidDirty,
			mNameDirty,
			mAddressDirty,
			mCityDirty,
			mPostcodeDirty,
			mSearchQueryDirty,
			mCuisinesDirty,
			mDealsDirty,
			mDefaultDisplayRankDirty,
			mIsHalalDirty,
			mIsNewDirty,
			mIsOpenNowForDeliveryDirty,
			mIsOpenNowForCollectionDirty,
			mIsOpenNowDirty,
			mIsSponsoredDirty,
			mIsTemporarilyOfflineDirty,
			mLogoStandardResUrlDirty,
			mRatingDirty,
			mReasonWhyTemporarilyOfflineDirty,
			mNumRatingsDirty,
			mDescriptionDirty,
			mLatitudeDirty,
			mLongitudeDirty,
			mOpeningTimeDirty,
			mUniqueNameDirty,
			mDriveDistanceDirty,
			mRatingAverageDirty,
			mShowSmileyDirty,
			mSmileyDateDirty,
			mSmileyResultDirty,
			mSmileyEliteDirty,
			mSmileyUrlDirty,
			mDealDisplayRankDirty,
			mHasDealsDirty,
			mMaxDiscountPercentDirty
		});
	}
	
	@Override
	protected AbstractValuesBuilder createBuilder() {
		Builder builder = Restaurants.newBuilder();

		if(mJeidDirty) {
			builder.setJeid(mJeid);
		}
		if(mNameDirty) {
			builder.setName(mName);
		}
		if(mAddressDirty) {
			builder.setAddress(mAddress);
		}
		if(mCityDirty) {
			builder.setCity(mCity);
		}
		if(mPostcodeDirty) {
			builder.setPostcode(mPostcode);
		}
		if(mSearchQueryDirty) {
			builder.setSearchQuery(mSearchQuery);
		}
		if(mCuisinesDirty) {
			builder.setCuisines(mCuisines);
		}
		if(mDealsDirty) {
			builder.setDeals(mDeals);
		}
		if(mDefaultDisplayRankDirty) {
			builder.setDefaultDisplayRank(mDefaultDisplayRank);
		}
		if(mIsHalalDirty) {
			builder.setIsHalal(mIsHalal);
		}
		if(mIsNewDirty) {
			builder.setIsNew(mIsNew);
		}
		if(mIsOpenNowForDeliveryDirty) {
			builder.setIsOpenNowForDelivery(mIsOpenNowForDelivery);
		}
		if(mIsOpenNowForCollectionDirty) {
			builder.setIsOpenNowForCollection(mIsOpenNowForCollection);
		}
		if(mIsOpenNowDirty) {
			builder.setIsOpenNow(mIsOpenNow);
		}
		if(mIsSponsoredDirty) {
			builder.setIsSponsored(mIsSponsored);
		}
		if(mIsTemporarilyOfflineDirty) {
			builder.setIsTemporarilyOffline(mIsTemporarilyOffline);
		}
		if(mLogoStandardResUrlDirty) {
			builder.setLogoStandardResUrl(mLogoStandardResUrl);
		}
		if(mRatingDirty) {
			builder.setRating(mRating);
		}
		if(mReasonWhyTemporarilyOfflineDirty) {
			builder.setReasonWhyTemporarilyOffline(mReasonWhyTemporarilyOffline);
		}
		if(mNumRatingsDirty) {
			builder.setNumRatings(mNumRatings);
		}
		if(mDescriptionDirty) {
			builder.setDescription(mDescription);
		}
		if(mLatitudeDirty) {
			builder.setLatitude(mLatitude);
		}
		if(mLongitudeDirty) {
			builder.setLongitude(mLongitude);
		}
		if(mOpeningTimeDirty) {
			builder.setOpeningTime(mOpeningTime);
		}
		if(mUniqueNameDirty) {
			builder.setUniqueName(mUniqueName);
		}
		if(mDriveDistanceDirty) {
			builder.setDriveDistance(mDriveDistance);
		}
		if(mRatingAverageDirty) {
			builder.setRatingAverage(mRatingAverage);
		}
		if(mShowSmileyDirty) {
			builder.setShowSmiley(mShowSmiley);
		}
		if(mSmileyDateDirty) {
			builder.setSmileyDate(mSmileyDate);
		}
		if(mSmileyResultDirty) {
			builder.setSmileyResult(mSmileyResult);
		}
		if(mSmileyEliteDirty) {
			builder.setSmileyElite(mSmileyElite);
		}
		if(mSmileyUrlDirty) {
			builder.setSmileyUrl(mSmileyUrl);
		}
		if(mDealDisplayRankDirty) {
			builder.setDealDisplayRank(mDealDisplayRank);
		}
		if(mHasDealsDirty) {
			builder.setHasDeals(mHasDeals);
		}
		if(mMaxDiscountPercentDirty) {
			builder.setMaxDiscountPercent(mMaxDiscountPercent);
		}
		
		return builder;
	}
	
    @Override
	public void makeDirty(boolean dirty){
		mJeidDirty = dirty;
		mNameDirty = dirty;
		mAddressDirty = dirty;
		mCityDirty = dirty;
		mPostcodeDirty = dirty;
		mSearchQueryDirty = dirty;
		mCuisinesDirty = dirty;
		mDealsDirty = dirty;
		mDefaultDisplayRankDirty = dirty;
		mIsHalalDirty = dirty;
		mIsNewDirty = dirty;
		mIsOpenNowForDeliveryDirty = dirty;
		mIsOpenNowForCollectionDirty = dirty;
		mIsOpenNowDirty = dirty;
		mIsSponsoredDirty = dirty;
		mIsTemporarilyOfflineDirty = dirty;
		mLogoStandardResUrlDirty = dirty;
		mRatingDirty = dirty;
		mReasonWhyTemporarilyOfflineDirty = dirty;
		mNumRatingsDirty = dirty;
		mDescriptionDirty = dirty;
		mLatitudeDirty = dirty;
		mLongitudeDirty = dirty;
		mOpeningTimeDirty = dirty;
		mUniqueNameDirty = dirty;
		mDriveDistanceDirty = dirty;
		mRatingAverageDirty = dirty;
		mShowSmileyDirty = dirty;
		mSmileyDateDirty = dirty;
		mSmileyResultDirty = dirty;
		mSmileyEliteDirty = dirty;
		mSmileyUrlDirty = dirty;
		mDealDisplayRankDirty = dirty;
		mHasDealsDirty = dirty;
		mMaxDiscountPercentDirty = dirty;
	}

	@Override
	protected void setPropertiesFromCursor(Cursor c) {
		setId(c.getLong(Indices._ID));
		setJeid(c.getLong(Indices.JEID));
		setName(c.getString(Indices.NAME));
		setAddress(c.getString(Indices.ADDRESS));
		setCity(c.getString(Indices.CITY));
		setPostcode(c.getString(Indices.POSTCODE));
		setSearchQuery(c.getString(Indices.SEARCH_QUERY));
		setCuisines(c.getString(Indices.CUISINES));
		setDeals(c.getString(Indices.DEALS));
		setDefaultDisplayRank(c.getLong(Indices.DEFAULT_DISPLAY_RANK));
		setIsHalal(c.getInt(Indices.IS_HALAL) > 0);
		setIsNew(c.getInt(Indices.IS_NEW) > 0);
		setIsOpenNowForDelivery(c.getInt(Indices.IS_OPEN_NOW_FOR_DELIVERY) > 0);
		setIsOpenNowForCollection(c.getInt(Indices.IS_OPEN_NOW_FOR_COLLECTION) > 0);
		setIsOpenNow(c.getInt(Indices.IS_OPEN_NOW) > 0);
		setIsSponsored(c.getInt(Indices.IS_SPONSORED) > 0);
		setIsTemporarilyOffline(c.getInt(Indices.IS_TEMPORARILY_OFFLINE) > 0);
		setLogoStandardResUrl(c.getString(Indices.LOGO_STANDARD_RES_URL));
		setRating(c.getDouble(Indices.RATING));
		setReasonWhyTemporarilyOffline(c.getString(Indices.REASON_WHY_TEMPORARILY_OFFLINE));
		setNumRatings(c.getLong(Indices.NUM_RATINGS));
		setDescription(c.getString(Indices.DESCRIPTION));
		setLatitude(c.getDouble(Indices.LATITUDE));
		setLongitude(c.getDouble(Indices.LONGITUDE));
		setOpeningTime(c.getLong(Indices.OPENING_TIME));
		setUniqueName(c.getString(Indices.UNIQUE_NAME));
		setDriveDistance(c.getDouble(Indices.DRIVE_DISTANCE));
		setRatingAverage(c.getDouble(Indices.RATING_AVERAGE));
		setShowSmiley(c.getInt(Indices.SHOW_SMILEY) > 0);
		setSmileyDate(c.getLong(Indices.SMILEY_DATE));
		setSmileyResult(c.getLong(Indices.SMILEY_RESULT));
		setSmileyElite(c.getInt(Indices.SMILEY_ELITE) > 0);
		setSmileyUrl(c.getString(Indices.SMILEY_URL));
		setDealDisplayRank(c.getLong(Indices.DEAL_DISPLAY_RANK));
		setHasDeals(c.getInt(Indices.HAS_DEALS) > 0);
		setMaxDiscountPercent(c.getLong(Indices.MAX_DISCOUNT_PERCENT));
	}
	
	public static RestaurantsRecord fromCursor(Cursor c) {
	    RestaurantsRecord item = new RestaurantsRecord();
	    
		item.setPropertiesFromCursor(c);
		
		item.makeDirty(false);
		
	    return item;
	}
	
	public static RestaurantsRecord fromBundle(Bundle bundle, String key) {
		bundle.setClassLoader(RestaurantsRecord.class.getClassLoader());
		return bundle.getParcelable(key);
	}
	
	public static RestaurantsRecord get(long id) {
	    Cursor c = null;
	    
	    ContentResolver resolver = Mechanoid.getContentResolver();
	    
	    try {
	        c = resolver.query(Restaurants.CONTENT_URI.buildUpon()
			.appendPath(String.valueOf(id)).build(), PROJECTION, null, null, null);
	        
	        if(!c.moveToFirst()) {
	            return null;
	        }
	        
	        return fromCursor(c);
	    } finally {
	        Closeables.closeSilently(c);
	    }
	}
}
